import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Popups from './components/Popups'
import { PopupProvider } from './context/PopupProvider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// add the modal again to the layout
// if you want the parallel routes
export default function RootLayout({children,modal}: { children: React.ReactNode,modal:React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PopupProvider>
        {children}
        <Popups/>
        </PopupProvider>
        </body>

    </html>
  )
}
